export const PRODUCTS_WITH_META_DATA = {
  totalCount: 56,
  list: [
    {
      id: "3f6389bf-4bdb-4575-940b-7682f9350637",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 350184,
      comparePrice: 0,
      sku: "KA04AD0079",
      isInStock: true,
      urlPart: "altigreen-neev-16",
      formattedComparePrice: "",
      formattedPrice: "₹350,184.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Altigreen neEV",
      media: [
        {
          url: "a66d89_f1c8be5c3c7d4dff89c69dd0574a0bd5~mv2.jpg",
          index: 0,
          width: 575,
          mediaType: "PHOTO",
          altText: null,
          title: "6440dd2a0446543e15a220cc_tez-internal.jpg",
          height: 360,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "f259021f-8c2d-473c-be3d-7f5ac461ef0e",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 347725,
      comparePrice: 0,
      sku: "KA04AD0080",
      isInStock: true,
      urlPart: "altigreen-neev-15",
      formattedComparePrice: "",
      formattedPrice: "₹347,725.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Altigreen neEV",
      media: [
        {
          url: "a66d89_f1c8be5c3c7d4dff89c69dd0574a0bd5~mv2.jpg",
          index: 0,
          width: 575,
          mediaType: "PHOTO",
          altText: null,
          title: "6440dd2a0446543e15a220cc_tez-internal.jpg",
          height: 360,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "b237594e-77a2-4d89-814a-8a3ca4e2679b",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 290000,
      comparePrice: 0,
      sku: "KA04AC7768",
      isInStock: true,
      urlPart: "altigreen-neev-14",
      formattedComparePrice: "",
      formattedPrice: "₹290,000.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Altigreen neEV",
      media: [
        {
          url: "a66d89_f1c8be5c3c7d4dff89c69dd0574a0bd5~mv2.jpg",
          index: 0,
          width: 575,
          mediaType: "PHOTO",
          altText: null,
          title: "6440dd2a0446543e15a220cc_tez-internal.jpg",
          height: 360,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "4319d215-a238-4951-9c0b-2cfd1abe9b16",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 314569,
      comparePrice: 0,
      sku: "KA04AC8271",
      isInStock: true,
      urlPart: "altigreen-neev-13",
      formattedComparePrice: "",
      formattedPrice: "₹314,569.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Altigreen neEV",
      media: [
        {
          url: "a66d89_f1c8be5c3c7d4dff89c69dd0574a0bd5~mv2.jpg",
          index: 0,
          width: 575,
          mediaType: "PHOTO",
          altText: null,
          title: "6440dd2a0446543e15a220cc_tez-internal.jpg",
          height: 360,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "bf273b5b-5bf5-4a50-aebf-b629694cc82d",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 261827,
      comparePrice: 0,
      sku: "AP39UH4886",
      isInStock: true,
      urlPart: "mahindra-treo-zor-5",
      formattedComparePrice: "",
      formattedPrice: "₹261,827.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Mahindra Treo Zor",
      media: [
        {
          url: "a66d89_7c1f7b0e34fd44a3b799641106dc3d1a~mv2.jpg",
          index: 0,
          width: 600,
          mediaType: "PHOTO",
          altText: null,
          title: "Whats-App-Image-2024-05-22-at-12-11-01-2-1.jpg",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "07a5423b-2151-429a-8860-8654f248afcd",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 353872,
      comparePrice: 0,
      sku: "DL51GD9536",
      isInStock: true,
      urlPart: "altigreen-neev-12",
      formattedComparePrice: "",
      formattedPrice: "₹353,872.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Altigreen neEV",
      media: [
        {
          url: "a66d89_2d44d6914ad14400af8176afe658114a~mv2.jpg",
          index: 0,
          width: 358,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "ce92b6fa-a58d-48cd-9a8c-544d090364ea",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 259434,
      comparePrice: 0,
      sku: "TS30TA4819",
      isInStock: true,
      urlPart: "mahindra-treo-zor-4",
      formattedComparePrice: "",
      formattedPrice: "₹259,434.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Mahindra Treo Zor",
      media: [
        {
          url: "a66d89_17d6a5e8f3f14692b80ddd8031a8a5d0~mv2.jpg",
          index: 0,
          width: 600,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "7c7d28b4-61b4-421c-887e-1c6bc0ea3158",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 272092,
      comparePrice: 0,
      sku: "TS11UD2371",
      isInStock: true,
      urlPart: "mahindra-treo-zor-3",
      formattedComparePrice: "",
      formattedPrice: "₹272,092.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Mahindra Treo Zor",
      media: [
        {
          url: "a66d89_7c1f7b0e34fd44a3b799641106dc3d1a~mv2.jpg",
          index: 0,
          width: 600,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "e155a9a8-d04b-4c4d-9a26-dde2b3325f76",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 303041,
      comparePrice: 0,
      sku: "TS07UK8512",
      isInStock: true,
      urlPart: "altigreen-neev-11",
      formattedComparePrice: "",
      formattedPrice: "₹303,041.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Altigreen neEV",
      media: [
        {
          url: "a66d89_3f0975745547492093339699098e6154~mv2.jpeg",
          index: 0,
          width: 1200,
          mediaType: "PHOTO",
          altText: null,
          title: "WhatsApp Image 2024-05-29 at 13.34.51.jpeg",
          height: 1600,
        },
        {
          url: "a66d89_d6d6c9600c2f4b4f805673ff7e18f640~mv2.jpeg",
          index: 1,
          width: 1200,
          mediaType: "PHOTO",
          altText: null,
          title: "WhatsApp Image 2024-05-29 at 13.34.51 (1).jpeg",
          height: 1600,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "aef83e07-75ea-4247-bccd-94d3c5cfad79",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 312306,
      comparePrice: 0,
      sku: "TS07UM3252",
      isInStock: true,
      urlPart: "piaggio-fx-6",
      formattedComparePrice: "",
      formattedPrice: "₹312,306.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Piaggio fx",
      media: [
        {
          url: "a66d89_7d47e9f3646e42bcb96b719c4334c624~mv2.jpg",
          index: 0,
          width: 600,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "331fcffc-6f2e-44a2-aa84-3a9ec1090bc3",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 200000,
      comparePrice: 0,
      sku: "KA19AD7789",
      isInStock: true,
      urlPart: "osm-rage",
      formattedComparePrice: "",
      formattedPrice: "₹200,000.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "OSM Rage +",
      media: [
        {
          url: "a66d89_4f3737e9f77b4d50a30ea521458c9775~mv2.jpg",
          index: 0,
          width: 600,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "2b8b8bdb-6e49-45dd-9cda-b471dd1648da",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 235834,
      comparePrice: 0,
      sku: "AP39UJ4686",
      isInStock: true,
      urlPart: "mahindra-treo-zor-2",
      formattedComparePrice: "",
      formattedPrice: "₹235,834.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Mahindra Treo Zor",
      media: [
        {
          url: "a66d89_425f581f9dad4058b865350b60bb3579~mv2.jpg",
          index: 0,
          width: 1040,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 480,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "30f656fe-11b3-405d-896d-4c88b133dae5",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 360885,
      comparePrice: 0,
      sku: "MH10CQ3215",
      isInStock: true,
      urlPart: "altigreen-neev-10",
      formattedComparePrice: "",
      formattedPrice: "₹360,885.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Altigreen neEV",
      media: [
        {
          url: "a66d89_764e69bd810547e49f2904d7537deccc~mv2.jpg",
          index: 0,
          width: 600,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "36d0e740-96ba-4b23-bea3-35f20a7e2e14",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 287746,
      comparePrice: 0,
      sku: "TS07UK7538",
      isInStock: true,
      urlPart: "piaggio-fx-5",
      formattedComparePrice: "",
      formattedPrice: "₹287,746.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Piaggio fx",
      media: [
        {
          url: "a66d89_3ad9f366bfa941ca8b5996419f61cabd~mv2.jpg",
          index: 0,
          width: 800,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "261e9bde-55fe-4960-b025-ecfbff2ef19f",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 283226,
      comparePrice: 0,
      sku: "TS09UD8824",
      isInStock: true,
      urlPart: "mahindra-treo-zor-1",
      formattedComparePrice: "",
      formattedPrice: "₹283,226.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Mahindra Treo Zor",
      media: [
        {
          url: "a66d89_a9092b062e3a4f25b14818434151204b~mv2.jpg",
          index: 0,
          width: 1067,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "d22f4cc3-3593-4040-a0c9-3b7da3e4b764",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 318089,
      comparePrice: 0,
      sku: "KA04AC7772",
      isInStock: true,
      urlPart: "altigreen-neev-9",
      formattedComparePrice: "",
      formattedPrice: "₹318,089.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Altigreen neEV",
      media: [
        {
          url: "a66d89_ad5aad22e7b44af59a2ce99d5f530c39~mv2.jpg",
          index: 0,
          width: 600,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "e81ac5bc-4bc3-487a-921c-519a6cd0f71f",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 360334,
      comparePrice: 0,
      sku: "TN19AU6271",
      isInStock: true,
      urlPart: "euler-hiload-7",
      formattedComparePrice: "",
      formattedPrice: "₹360,334.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Euler Hiload",
      media: [
        {
          url: "a66d89_218afd4964ca41fe9fa7ce85ad746ba0~mv2.jpg",
          index: 0,
          width: 501,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "bae4741c-3ae3-40a6-9bcd-e980c6a91372",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 252572,
      comparePrice: 0,
      sku: "AP39UH3951",
      isInStock: true,
      urlPart: "mahindra-treo-zor",
      formattedComparePrice: "",
      formattedPrice: "₹252,572.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Mahindra Treo Zor",
      media: [],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "57c40794-0e22-4209-87e1-6ef30a2e69b4",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 278261,
      comparePrice: 0,
      sku: "KA05AL5063",
      isInStock: true,
      urlPart: "e-trio-touro-max",
      formattedComparePrice: "",
      formattedPrice: "₹278,261.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "E-TRIO Max++",
      media: [
        {
          url: "a66d89_71b1a6e1aed54443942740e9be42bcbc~mv2.jpg",
          index: 0,
          width: 600,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "f5e4cd38-3dd1-40d5-afde-079856fbe8de",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 290759,
      comparePrice: 0,
      sku: "DL51GD6350",
      isInStock: true,
      urlPart: "piaggio-fx-4",
      formattedComparePrice: "",
      formattedPrice: "₹290,759.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Piaggio fx",
      media: [
        {
          url: "a66d89_b79c7a7035c549cda7a34f895dc6da25~mv2.jpg",
          index: 0,
          width: 1280,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 720,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "58bf735d-1565-43d5-b494-9feb50ae3ce2",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 361929,
      comparePrice: 0,
      sku: "MH12VB4262",
      isInStock: true,
      urlPart: "euler-hiload-6",
      formattedComparePrice: "",
      formattedPrice: "₹361,929.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Euler Hiload",
      media: [
        {
          url: "a66d89_271dff73dbe247369d2eb0004977e9ee~mv2.jpg",
          index: 0,
          width: 600,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "abbee742-4410-4ee2-8c22-00046a9494e2",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 364632,
      comparePrice: 0,
      sku: "DL51EV0345",
      isInStock: true,
      urlPart: "altigreen-neev-8",
      formattedComparePrice: "",
      formattedPrice: "₹364,632.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Altigreen neEV",
      media: [
        {
          url: "a66d89_13930ba4d1674d0e8f17d329493f69ac~mv2.jpg",
          index: 0,
          width: 358,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "74a5efd6-3f7e-40ca-9fb5-3cec5db3a8e1",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 319921,
      comparePrice: 0,
      sku: "MH20EK2845",
      isInStock: true,
      urlPart: "piaggio-fx-max-7",
      formattedComparePrice: "",
      formattedPrice: "₹319,921.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Piaggio fx Max",
      media: [
        {
          url: "a66d89_a6fe9f0b81ba4844af520f1c2d0073a4~mv2.jpg",
          index: 0,
          width: 599,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
    {
      id: "614021d2-76b4-49f4-9362-6bd58a0df83c",
      options: [],
      customTextFields: [],
      productType: "physical",
      ribbon: "New",
      price: 344129,
      comparePrice: 0,
      sku: "MH20EK2746",
      isInStock: true,
      urlPart: "piaggio-fx-max-6",
      formattedComparePrice: "",
      formattedPrice: "₹344,129.00",
      pricePerUnit: null,
      formattedPricePerUnit: null,
      pricePerUnitData: null,
      itemDiscount: null,
      digitalProductFileItems: [],
      name: "Piaggio fx Max",
      media: [
        {
          url: "a66d89_4543b86e90a2469a9f97c906b071f0d8~mv2.jpg",
          index: 0,
          width: 599,
          mediaType: "PHOTO",
          altText: null,
          title: "",
          height: 800,
        },
      ],
      isManageProductItems: false,
      productItemsPreOrderAvailability: "no_variants",
      isTrackingInventory: false,
      inventory: {
        status: "in_stock",
        quantity: 0,
        availableForPreOrder: false,
        preOrderInfoView: {
          limit: null,
        },
      },
      subscriptionPlans: {
        list: [],
      },
      discount: {
        mode: "AMOUNT",
        value: 0,
      },
    },
  ],
};
